# See http://stylelint.io/user-guide/rules/
rules:
    # Color
    color-hex-case: lower
    color-hex-length: short
    color-named: never
    color-no-invalid-hex: true

    # Font family
    font-family-name-quotes: double-unless-keyword

    # Function
    function-calc-no-unspaced-operator: true
    function-comma-space-after: true
    function-max-empty-lines: 0
    function-name-case: lower
    function-url-quotes: double

    # Number
    number-leading-zero: never
    number-no-trailing-zeros: true
    number-zero-length-no-unit: true

    # String
    string-no-newline: true
    string-quotes: double

    # Unit
    unit-blacklist: ["pc", "in", "cm", "mm", "ex"]
    unit-case: lower
    unit-no-unknown: true

    # Value list
    value-list-comma-space-after: true

    # Shorthand property
    shorthand-property-no-redundant-values: true

    # Property
    property-case: true

    # Declaration
    declaration-bang-space-before: true
    declaration-colon-space-after: always-single-line
    declaration-colon-space-before: never
    declaration-no-important: true

    # Declaration block
    declaration-block-no-duplicate-properties: true
    declaration-block-no-shorthand-property-overrides: true
    declaration-block-semicolon-newline-after: always-multi-line
    declaration-block-semicolon-space-after: always-single-line
    declaration-block-single-line-max-declarations: 3
    declaration-block-trailing-semicolon: always

    # Block
    block-closing-brace-newline-after: always
    block-closing-brace-newline-before: always-multi-line
    block-closing-brace-space-after: never
    block-closing-brace-space-before: always-single-line
    block-no-empty: true
    block-opening-brace-newline-after: always-multi-line
    block-opening-brace-newline-before: never
    block-opening-brace-space-after: always-single-line
    block-opening-brace-space-before: always

    # Selector
    selector-combinator-space-after: always
    selector-combinator-space-before: always
    selector-no-id: true
    selector-pseudo-class-case: lower
    selector-pseudo-element-case: lower
    selector-pseudo-element-colon-notation: double
    selector-pseudo-element-no-unknown: true
    selector-type-case: lower
    selector-max-empty-lines: 0

    # Selector list
    selector-list-comma-newline-after: always
    selector-list-comma-newline-before: never

    # Root rule
    root-no-standard-properties: true

    # Rule
    rule-non-nested-empty-line-before: always-multi-line

    # Media feature
    media-feature-colon-space-after: always
    media-feature-colon-space-before: never
    media-feature-no-missing-punctuation: true
    media-feature-range-operator-space-after: always
    media-feature-range-operator-space-before: always

    # Media query list
    media-query-list-comma-space-after: always-single-line
    media-query-list-comma-space-before: never

    # At rule
    at-rule-empty-line-before: always
    at-rule-name-case: lower
    at-rule-name-space-after: always-single-line
    at-rule-semicolon-newline-after: always

    # General / Sheet
    indentation: 4
    max-empty-lines: 2
    max-nesting-depth: 4
    no-browser-hacks: true
    no-duplicate-selectors: true
    no-eol-whitespace: true
    no-extra-semicolons: true
    no-missing-eof-newline: true
    no-unknown-animations: true
    stylelint-disable-reason: always-before
