dist: trusty
language: node_js

node_js:
    - node

before_script:
# Disabled for now, until kaba is ported to TypeScriot
#    - npm run-script build
    - npm audit
    - npx prettier-package-json package.json --list-different --tab-width 4
    - npm test
