parser: babel-eslint

parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true
        experimentalObjectRestSpread: true

plugins:
    - react

settings:
    react:
        createClass: "Component"
        pragma: "h"
        version: "15.0"

env:
    browser: true
    commonjs: true

extends: 'eslint:recommended'

rules:
    # Possible Errors
    'valid-jsdoc':
        - warn
        - requireReturn: false
          requireParamDescription: false
          requireReturnDescription: false

    # Best Practices
    'block-scoped-var': error
    curly:
        - error
        - all
    'dot-location':
        - error
        - property
    eqeqeq:
        - error
        - smart
    'guard-for-in': error
    'no-caller': error
    'no-eval': error
    'no-extend-native': error
    'no-extra-label': error
    'no-floating-decimal': error
    'no-implicit-globals': error
    'no-implied-eval': error
    'no-invalid-this': error
    'no-iterator': error
    'no-labels': error
    'no-lone-blocks': error
    'no-loop-func': error
    'no-multi-spaces': warn
    'no-multi-str': error
    'no-new-func': error
    'no-new-wrappers': error
    'no-octal-escape': error
    'no-proto': error
    'no-prototype-builtins': error
    'no-redeclare': error
    'no-restricted-properties':
        - error
        - property: setInterval
          message: "Don't use setInterval. Use repeated setTimeout instead."
    'no-script-url': error
    'no-self-compare': warn
    'no-sequences': error
    'no-throw-literal': error
    'no-unmodified-loop-condition': error
    'no-unused-expressions': warn
    'no-useless-call': error
    'no-useless-concat': error
    'no-useless-escape': warn
    'no-void': error
    'no-warning-comments': warn
    'no-with': error
    'radix':
        - error
        - always
    'wrap-iife': error

    # Strict mode
    strict:
        - error
        - global

    # Variables
    'no-catch-shadow': error
    'no-label-var': error
    'no-restricted-globals': error
    'no-shadow-restricted-names': error
    'no-shadow': error
    'no-undef-init': error
    'no-unused-vars':
        - error
        - args: none
          argsIgnorePattern: '^_'
    'no-use-before-define':
        - error
        - classes: false
          functions: false

    # Node.js and CommonJS
    'global-require': error
    'no-new-require': warn

    # Stylistic Issues
    'block-spacing':
        - warn
        - always
    'camelcase':
        - error
        - properties: always
    'comma-dangle':
        - warn
        - "always-multiline"
    'comma-spacing':
        - warn
        - before: false
          after: true
    'comma-style':
        - warn
        - last
    'consistent-this':
        - error
        - self
    'eol-last': error
    'func-call-spacing': warn
    'func-names':
        - warn
        - never
    'indent':
        - warn
        - 4
        - SwitchCase: 1
    'key-spacing':
        - warn
        - beforeColon: false
          afterColon: true
          mode: strict
    'linebreak-style':
        - error
        - unix
    'max-depth':
        - warn
        - 4
    'max-nested-callbacks':
        - error
        - 3
    'max-params':
        - warn
        - 4
    'max-statements-per-line':
        - warn
        - max: 1
    'new-cap': error
    'new-parens': error
    'newline-per-chained-call': warn
    'no-array-constructor': error
    'no-bitwise': warn
    'no-inline-comments': warn
    'no-lonely-if': warn
    'no-mixed-operators': error
    'no-multiple-empty-lines': warn
    'no-nested-ternary': error
    'no-new-object': error
    'no-plusplus':
        - error
        - allowForLoopAfterthoughts: true
    'no-spaced-func': error
    'no-tabs': error
    'no-underscore-dangle': error
    'no-unneeded-ternary': error
    'no-whitespace-before-property': error
    'object-property-newline': warn
    'one-var-declaration-per-line':
        - error
        - always
    'require-jsdoc':
        - warn
        - require:
            FunctionDeclaration: true
            MethodDefinition: true
            ClassDeclaration: false
    'semi':
        - error
        - always
    'space-before-blocks':
        - warn
        - always
    'space-before-function-paren':
        - warn
        - always
    'space-infix-ops': error
    'unicode-bom':
        - error
        - never

    # ECMAScript 6
    'arrow-spacing': warn
    'generator-star-spacing': warn
    'no-confusing-arrow': warn
    'no-duplicate-imports': warn
    'no-useless-computed-key': warn
    'no-useless-constructor': error
    'no-useless-rename': warn
    'no-var': error
    'prefer-arrow-callback': warn
    'prefer-rest-params': error
    'prefer-spread': error

    # React
    'react/forbid-component-props': warn
    'react/no-children-prop': warn
    'react/no-danger': error
    'react/no-danger-with-children': error
    'react/no-did-mount-set-state': warn
    'react/no-did-update-set-state': warn
    'react/no-direct-mutation-state': error
    'react/no-multi-comp': error
    'react/no-render-return-value': error
    'react/no-string-refs': error
    'react/no-unescaped-entities': error
    'react/no-will-update-set-state': error
    'react/prefer-es6-class':
        - error
        - "always"
    'react/require-render-return': warn
    'react/self-closing-comp': warn
    'react/void-dom-elements-no-children': error
    'react/jsx-equals-spacing':
        - warn
        - "never"
    'react/jsx-filename-extension': error
    'react/jsx-indent':
        - warn
        - 4
    'react/jsx-indent-props':
        - warn
        - 4
    'react/jsx-no-duplicate-props': error
    'react/jsx-no-undef': error
    'react/jsx-pascal-case': error
    'react/jsx-uses-react': error
    'react/jsx-uses-vars': error
